# Juju OpenStack environment parameters
network: net04
use-floating-ip: true
control-bucket: juju-environment

# Keystone authentication parameters
auth-url: http://172.20.4.10:5000/v2.0
region: RegionOne
tenant-name: admin
username: admin
password: admin

# Mapping of Juju series to cloud images
series:
  trusty:
    name: juju-ubuntu-server-14.04-x64
    url: http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
  precise:
    name: juju-ubuntu-server-12.04-x64
    url: http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-amd64-disk1.img
